/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#f8f9ff',
        'secondary-fixed-dim': '#c6c6c7',
        'on-secondary-fixed': '#1a1c1c',
        'on-primary-fixed': '#091b37',
        background: '#f8f9ff',
        primary: '#041632',
        'surface-container': '#e5eeff',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#3a2800',
        'secondary-fixed': '#e2e2e2',
        'on-secondary-fixed-variant': '#454747',
        'on-tertiary-container': '#b08d48',
        error: '#ba1a1a',
        'on-surface': '#0b1c30',
        outline: '#75777e',
        secondary: '#5d5f5f',
        'surface-variant': '#d3e4fe',
        'on-primary': '#ffffff',
        'on-error-container': '#93000a',
        'tertiary-fixed': '#ffdea5',
        'inverse-surface': '#213145',
        'outline-variant': '#c5c6ce',
        'on-secondary-container': '#616363',
        'on-background': '#0b1c30',
        'on-tertiary-fixed-variant': '#5d4201',
        'surface-container-highest': '#d3e4fe',
        'tertiary-fixed-dim': '#e9c176',
        'on-surface-variant': '#44474d',
        'primary-fixed-dim': '#b7c7eb',
        'inverse-on-surface': '#eaf1ff',
        'primary-container': '#1b2b48',
        'inverse-primary': '#b7c7eb',
        'on-error': '#ffffff',
        'primary-fixed': '#d7e2ff',
        tertiary: '#201500',
        'on-primary-fixed-variant': '#374765',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed': '#261900',
        'surface-container-low': '#eff4ff',
        'surface-dim': '#cbdbf5',
        'error-container': '#ffdad6',
        'surface-tint': '#4f5e7e',
        'on-primary-container': '#8393b5',
        'surface-bright': '#f8f9ff',
        'secondary-container': '#dfe0e0',
        'surface-container-high': '#dce9ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '12px',
        lg: '48px',
        gutter: '24px',
        base: '8px',
        md: '24px',
        xl: '80px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        'body-md': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'display-lg-mobile': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        caption: ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-sm': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'display-lg-mobile': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        caption: ['12px', { lineHeight: '1.4', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '1', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-md': ['32px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
